source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'nokogiri'
gem 'json'
gem 'shotgun'
gem 'sanitize'
gem 'puma'
gem 'haml'
gem 'padrino'
gem 'sinatra-respond_to'
gem 'mechanize', "=2.7.0"
gem 'thin'
gem 'sinatra-asset-pipeline'
gem 'susy'
gem 'compass'
gem 'sinatra-static-assets'
gem 'dalli'
gem 'memcachier'
gem 'chronic'